on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: linting
      uses: alexanderdamiani/pylinter@v1.4.3
      with:
        python-root: '.'
        flake8-flags: '--ignore=E402,E501,E221 --count --show-source --statistics'
        skip-mypy: true
        mypy-flags: '--ignore-missing-imports'
        skip-isort: true
        fail-on-isort: true
